# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Keon Monroe 🌏
email: keon.monroe@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
Hi, I'm Keon! Based in Philadelphia with a passion for geospatial and mapping data that matters. Coding is my superpower, with Python, JavaScript, and R as my sidekicks. When I power down, I'm an eco-warrior🌲, yoga enthusiast 🧘, and proud dog parent 🐶. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kdmonroe.github.io" # the base hostname & protocol for your site, e.g. http://example.com
avatar: /assets/avy.jpg

# Social Links 
github_username:  kdmonroe
mastodon:
  username: kmonroe
  instance: mapstodon.space


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - about.md
  - portfolio.md

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
